### ISSUE TITLE
php start.php start报这个错

### ISSUE THREAD

**Issue by lh1003** [Tinywan/webman-admin#1]
![image](https://user-images.githubusercontent.com/64941432/160516229-82e96d16-206c-4cdd-9d2e-933226795e41.png)

**Comment by Tinywan** [comment]
你这是没Redis配置`config/redis.php`

**Comment by lh1003** [comment]
好的感谢

**Comment by theonewu** [comment]
php扩展里需要启用redis
然后开一个redis服务器。如果windows系统，可以使用win版的3.0.504作为开发使用。
如果是windows下开发，用最新版的webman创建个工程。将其windows.bat，windows.php和process下的monitor.php复制和覆盖。
然后使用控制台 ./windows.bat就可以开始开发了。
我踩了一天的坑，搞定了。希望作者使用官方的webman，不要进行删减，照顾一下windows系统开发者。

**Comment by Tinywan** [comment]
谢谢分享！一直在Linux下开发，Windows下确实没有考虑到。
