### ISSUE TITLE
你这个能否重新整理一下，太乱了，windows开发者很不适应

### ISSUE THREAD

**Issue by laogit** [Tinywan/webman-admin#13]
代码根本运行不起来啊，大神

**Comment by laogit** [comment]
{"code":0,"msg":"\u8def\u7531\u5730\u5740\u4e0d\u5b58\u5728","data":{"domain":"127.0.0.1:8888","method":"GET","request_url":"GET \/","timestamp":"2024-10-13 17:39:50","client_ip":"127.0.0.1","request_param":[],"error_message":"\u8def\u7531\u5730\u5740\u4e0d\u5b58\u5728","error_trace":["#0 G:\\soft_develop\\zhibo\\webman-admin-main\\vendor\\workerman\\webman-framework\\src\\App.php(159): Webman\\Route::{closure}()","#1 G:\\soft_develop\\zhibo\\webman-admin-main\\vendor\\workerman\\workerman\\Connection\\TcpConnection.php(646): Webman\\App->onMessage()","#2 G:\\soft_develop\\zhibo\\webman-admin-main\\vendor\\workerman\\workerman\\Events\\Select.php(311): Workerman\\Connection\\TcpConnection->baseRead()","#3 G:\\soft_develop\\zhibo\\webman-admin-main\\vendor\\workerman\\workerman\\Worker.php(1485): Workerman\\Events\\Select->loop()","#4 G:\\soft_develop\\zhibo\\webman-admin-main\\vendor\\workerman\\workerman\\Worker.php(1402): Workerman\\Worker::forkWorkersForWindows()","#5 G:\\soft_develop\\zhibo\\webman-admin-main\\vendor\\workerman\\workerman\\Worker.php(560): Workerman\\Worker::forkWorkers()","#6 G:\\soft_develop\\zhibo\\webman-admin-main\\vendor\\workerman\\webman-framework\\src\\support\\App.php(131): Workerman\\Worker::runAll()","#7 G:\\soft_develop\\zhibo\\webman-admin-main\\start.php(4): support\\App::run()","#8 {main}"],"file":"G:\\soft_develop\\zhibo\\webman-admin-main\\config\\route.php","line":67}}
![image](https://github.com/user-attachments/assets/a565a54c-b6eb-4bd4-bd7e-459bf025a9db)

**Comment by Tinywan** [comment]
你这是提示路由地址不存在，为什么要在windows开发
