### ISSUE TITLE
好像跨域没有作用

### ISSUE THREAD

**Issue by f236964158** [Tinywan/webman-admin#2]
![QQ截图20220406114935](https://user-images.githubusercontent.com/26860825/161892078-668da698-6a6c-48a3-abb6-2f64ab7163eb.png)
前端页面中提示跨域问题

**Comment by Tinywan** [comment]
http://localhost:2800/ 试试

**Comment by f236964158** [comment]
已通过更新 webman 版本 解决 谢谢
