### ISSUE TITLE
文件上传提示文件数量过多，超出系统文件数量限制

### ISSUE THREAD

**Issue by Jack126** [Tinywan/webman-admin#6]
使用 https://www.workerman.net/plugin/21  中
Tinywan\Storage\Storage::config(); // 初始化。 默认为本地存储：local，阿里云：oss，腾讯云：cos，七牛：qiniu
$res = Tinywan\Storage\Storage::uploadFile();
var_dump(json_encode($res));

方式，默认storage，local配置。提示如题错误。

AdapterAbstract.php  83,84 行 isfileupload ？？

**Comment by Tinywan** [comment]
卸载插件，重新安装试试

**Comment by Jack126** [comment]
vendor 删除重新composer  install ，storage 版本0.3.3，问题依旧。
